version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    restart: always
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - "5432"
  backend:
    container_name: foodgram-back
    build: ../backend/
    restart: always
    env_file: ../.env
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media
    expose:
      - "8000"
  frontend:
    container_name: foodgram-front
    build: ../frontend
    command: cp -r /app/build/. /static/
    volumes:
      - ../frontend/:/app/result_build/
      - static:/static/
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/app/static
      - media:/app/media
