# Generated by Django 3.2.16 on 2025-05-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_auto_20250510_2006"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="ingredient",
            new_name="ingredients",
        ),
    ]
