# Generated by Django 3.2.16 on 2025-05-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_rename_ingredient_recipe_ingredients"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={
                "verbose_name": "ингредиент в рецепте",
                "verbose_name_plural": "Ингредиенты в рецептах",
            },
        ),
    ]
